permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: chanteP
  email: 541149506@qq.com
  link: http://neetproject.com
  github: http://github.com/chanteP
  ua: UA-57857767-1

